var h;h||=typeof Module != 'undefined' ? Module : {};var aa=globalThis.document?.currentScript?.src,ba="",ca;try{ba=(new URL(".",aa)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),k=console.error.bind(console),ea,l=!1,fa,m,p,ha,ia,t,u,v,x,ja;
function ka(){var a=la.buffer;m=new Int8Array(a);ha=new Int16Array(a);p=new Uint8Array(a);ia=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);x=new Float64Array(a);ja=new BigInt64Array(a);new BigUint64Array(a)}function y(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);l=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ma;
async function na(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==ma&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),y(d)}}
async function pa(a){var b=ma;if(!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ra=a=>{for(;0<a.length;)a.shift()(h)},sa=[],ta=[],ua=()=>{var a=h.preRun.shift();ta.push(a)},wa=0,xa=null,ya=!0,za=globalThis.TextDecoder&&new TextDecoder,z=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&za)return za.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Aa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ba=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Aa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ca=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Da=()=>a=>crypto.getRandomValues(a),Ea=a=>{(Ea=Da())(a)},Fa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Aa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ga=[],Ha=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ia=a=>{var b=Array(Ha(a)+1);a=C(a,b,0,b.length);b.length=a;return b},Ja=
[];function Ka(a,b){Ja[a]={input:[],output:[],Fe:b};La(a,Ma)}
var Ma={open(a){var b=Ja[a.node.lf];if(!b)throw new D(43);a.qe=b;a.seekable=!1},close(a){a.qe.Fe.$e(a.qe)},$e(a){a.qe.Fe.$e(a.qe)},read(a,b,c,d){if(!a.qe||!a.qe.Fe.Pf)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.qe.Fe.Pf(a.qe)}catch(n){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Me=Date.now());return e},write(a,b,c,d){if(!a.qe||!a.qe.Fe.Cf)throw new D(60);try{for(var e=0;e<d;e++)a.qe.Fe.Cf(a.qe,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.xe=a.node.se=Date.now());return e}},Na={Pf(){a:{if(!Ga.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ga=Ia(a)}a=Ga.shift()}return a},Cf(a,b){null===b||10===b?(da(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},$e(a){0<a.output?.length&&(da(z(a.output)),a.output=[])},og(){return{Hg:25856,Jg:5,Gg:191,Ig:35387,Fg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},pg(){return 0},qg(){return[24,
80]}},Oa={Cf(a,b){null===b||10===b?(k(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},$e(a){0<a.output?.length&&(k(z(a.output)),a.output=[])}},E={ze:null,Ee(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.ze||(E.ze={dir:{node:{Le:E.pe.Le,Be:E.pe.Be,Ve:E.pe.Ve,gf:E.pe.gf,Xf:E.pe.Xf,cg:E.pe.cg,Yf:E.pe.Yf,Df:E.pe.Df,nf:E.pe.nf},stream:{ye:E.le.ye}},file:{node:{Le:E.pe.Le,Be:E.pe.Be},stream:{ye:E.le.ye,read:E.le.read,write:E.le.write,
Sf:E.le.Sf,Uf:E.le.Uf}},link:{node:{Le:E.pe.Le,Be:E.pe.Be,We:E.pe.We},stream:{}},Mf:{node:{Le:E.pe.Le,Be:E.pe.Be},stream:Pa}});c=Qa(a,b,c,d);16384===(c.mode&61440)?(c.pe=E.ze.dir.node,c.le=E.ze.dir.stream,c.oe={}):32768===(c.mode&61440)?(c.pe=E.ze.file.node,c.le=E.ze.file.stream,c.re=0,c.oe=null):40960===(c.mode&61440)?(c.pe=E.ze.link.node,c.le=E.ze.link.stream):8192===(c.mode&61440)&&(c.pe=E.ze.Mf.node,c.le=E.ze.Mf.stream);c.Me=c.xe=c.se=Date.now();a&&(a.oe[b]=c,a.Me=a.xe=a.se=c.Me);return c},Vg(a){return a.oe?
a.oe.subarray?a.oe.subarray(0,a.re):new Uint8Array(a.oe):new Uint8Array(0)},pe:{Le(a){var b={};b.Ng=8192===(a.mode&61440)?a.id:1;b.Xg=a.id;b.mode=a.mode;b.ah=1;b.uid=0;b.Wg=0;b.lf=a.lf;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.re:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Me=new Date(a.Me);b.xe=new Date(a.xe);b.se=new Date(a.se);b.gg=4096;b.Dg=Math.ceil(b.size/b.gg);return b},Be(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==
b.size&&(b=b.size,a.re!=b&&(0==b?(a.oe=null,a.re=0):(c=a.oe,a.oe=new Uint8Array(b),c&&a.oe.set(c.subarray(0,Math.min(b,a.re))),a.re=b)))},Ve(){E.sf||(E.sf=new D(44),E.sf.stack="<generic error, no stack>");throw E.sf;},gf(a,b,c,d){return E.createNode(a,b,c,d)},Xf(a,b,c){try{var d=Ra(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.oe)throw new D(55);e=Sa(d.parent.id,d.name);if(F[e]===d)F[e]=d.Pe;else for(e=F[e];e;){if(e.Pe===d){e.Pe=d.Pe;break}e=e.Pe}}delete a.parent.oe[a.name];b.oe[c]=
a;a.name=c;b.se=b.xe=a.parent.se=a.parent.xe=Date.now()},cg(a,b){delete a.oe[b];a.se=a.xe=Date.now()},Yf(a,b){var c=Ra(a,b),d;for(d in c.oe)throw new D(55);delete a.oe[b];a.se=a.xe=Date.now()},Df(a){return[".","..",...Object.keys(a.oe)]},nf(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},We(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},le:{read(a,b,c,d,e){var f=a.node.oe;if(e>=a.node.re)return 0;a=Math.min(a.node.re-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=
0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.xe=a.se=Date.now();if(b.subarray&&(!a.oe||a.oe.subarray)){if(f)return a.oe=b.subarray(c,c+d),a.re=d;if(0===a.re&&0===e)return a.oe=b.slice(c,c+d),a.re=d;if(e+d<=a.re)return a.oe.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.oe?a.oe.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.oe,a.oe=new Uint8Array(f),0<a.re&&a.oe.set(g.subarray(0,a.re),0));if(a.oe.subarray&&
b.subarray)a.oe.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.oe[e+f]=b[c+f];a.re=Math.max(a.re,e+d);return d},ye(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.re);if(0>b)throw new D(28);return b},Sf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.oe;if(e&2||!a||a.buffer!==m.buffer){d=!0;y();e=void 0;if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;
return{fh:e,zg:d}},Uf(a,b,c,d){E.le.write(a,b,0,d,c,!1);return 0}}},Ta=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ua=[],Va=null,Wa={},Xa=[],Ya=1,F=null,Za=!1,$a=!0,ab={},D=class{name="ErrnoError";constructor(a){this.te=a}},bb=class{Ne={};node=null;get flags(){return this.Ne.flags}set flags(a){this.Ne.flags=a}get position(){return this.Ne.position}set position(a){this.Ne.position=a}},cb=class{pe={};le={};hf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Ee=a.Ee;this.id=Ya++;this.name=
b;this.mode=c;this.lf=d;this.Me=this.xe=this.se=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function db(a,b={}){if(!a)throw new D(44);b.uf??(b.uf=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=Va,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ca(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ba(e+"/"+a[f]);try{d=Ra(d,a[f])}catch(n){if(44===n?.te&&g&&b.tg)return{path:e};throw n;}!d.hf||g&&!b.uf||(d=d.hf.root);if(40960===(d.mode&61440)&&(!g||b.Ze)){if(!d.pe.We)throw new D(52);
d=d.pe.We(d);"/"===d.charAt(0)||(d=Ca(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function eb(a){for(var b;;){if(a===a.parent)return a=a.Ee.Tf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Sa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%F.length}
function Ra(a,b){var c=16384===(a.mode&61440)?(c=fb(a,"x"))?c:a.pe.Ve?0:2:54;if(c)throw new D(c);for(c=F[Sa(a.id,b)];c;c=c.Pe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.pe.Ve(a,b)}function Qa(a,b,c,d){a=new cb(a,b,c,d);b=Sa(a.parent.id,a.name);a.Pe=F[b];return F[b]=a}function gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function fb(a,b){if($a)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function hb(a,b){if(16384!==(a.mode&61440))return 54;try{return Ra(a,b),20}catch(c){}return fb(a,"wx")}function G(a){a=Xa[a];if(!a)throw new D(8);return a}function ib(a,b=-1){a=Object.assign(new bb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Xa[b])break a;throw new D(33);}a.fd=b;return Xa[b]=a}
function jb(a,b=-1){a=ib(a,b);a.le?.Rg?.(a);return a}function kb(a,b){var c=null?.le.Be,d=c?null:a;c??=a.pe.Be;if(!c)throw new D(63);c(d,b)}var Pa={open(a){a.le=Wa[a.node.lf].le;a.le.open?.(a)},ye(){throw new D(70);}};function La(a,b){Wa[a]={le:b}}
function lb(a,b){var c="/"===b;if(c&&Va)throw new D(10);if(!c&&b){var d=db(b,{uf:!1});b=d.path;d=d.node;if(d.hf)throw new D(10);if(16384!==(d.mode&61440))throw new D(54);}b={type:a,bh:{},Tf:b,sg:[]};a=a.Ee(b);a.Ee=b;b.root=a;c?Va=a:d&&(d.hf=b,d.Ee&&d.Ee.sg.push(b))}function mb(a,b,c){var d=db(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=hb(d,a);if(e)throw new D(e);if(!d.pe.gf)throw new D(63);return d.pe.gf(d,a,b,c)}
function H(a){return mb(a,16895,0)}function nb(a,b,c){"undefined"==typeof c&&(c=b,b=438);mb(a,b|8192,c)}function ob(a,b){if(!Fa(a))throw new D(44);var c=db(b,{parent:!0}).node;if(!c)throw new D(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=hb(c,b);if(d)throw new D(d);if(!c.pe.nf)throw new D(63);c.pe.nf(c,b,a)}
function pb(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=db(a,{Ze:!(b&131072),tg:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=mb(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new D(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==gb(b)||b&576)?31:fb(d,gb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?db(e,{Ze:!0}).node:e;if(16384===(e.mode&61440))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=fb(e,"w");if(g)throw new D(g);kb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=ib({node:d,path:eb(d),flags:b,seekable:!0,position:0,le:d.le,wg:[],error:!1});e.le.open&&e.le.open(e);f&&(c&=511,d="string"==typeof d?
db(d,{Ze:!0}).node:d,kb(d,{mode:c&4095|d.mode&-4096,se:Date.now(),Qg:void 0}));!h.logReadFiles||b&1||a in ab||(ab[a]=1);return e}function rb(a){if(null===a.fd)throw new D(8);a.zf&&(a.zf=null);try{a.le.close&&a.le.close(a)}catch(b){throw b;}finally{Xa[a.fd]=null}a.fd=null}function sb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.le.ye)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.le.ye(a,b,c);a.wg=[]}
function tb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(16384===(a.node.mode&61440))throw new D(31);if(!a.le.write)throw new D(28);a.seekable&&a.flags&1024&&sb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.le.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function ub(){var a="/";a="string"==typeof a?a:eb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Ba(a+"/"+c);try{H(a)}catch(d){if(20!=d.te)throw d;}}}}
function vb(a,b,c){a=Ba("/dev/"+a);var d=Ta(!!b,!!c);vb.Rf??(vb.Rf=64);var e=vb.Rf++<<8|0;La(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,n,r){for(var q=0,A=0;A<r;A++){try{var w=b()}catch(B){throw new D(29);}if(void 0===w&&0===q)throw new D(6);if(null===w||void 0===w)break;q++;g[n+A]=w}q&&(f.node.Me=Date.now());return q},write(f,g,n,r){for(var q=0;q<r;q++)try{c(g[n+q])}catch(A){throw new D(29);}r&&(f.node.xe=f.node.se=Date.now());return q}});nb(a,d,e)}var I={};
function wb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":G(a).path;if(0==b.length)throw new D(44);return a+"/"+b}
var xb=void 0,J=()=>{var a=t[+xb>>2];xb+=4;return a},yb=0,zb={},Ab=a=>{if(!(a instanceof qa||"unwind"==a))throw a;},Bb=a=>{fa=a;ya||0<yb||(h.onExit?.(a),l=!0);throw new qa(a);},Cb=()=>{if(!(ya||0<yb))try{var a=fa;fa=a;Bb(a)}catch(b){Ab(b)}},Db=a=>{if(!l)try{a(),Cb()}catch(b){Ab(b)}},Eb=[0,document,window],Fb=a=>{a=2<a?a?z(p,a):"":a;return Eb[a]||document.querySelector(a)},Gb=a=>0>Eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
function Hb(a){var b=K.ve[a];b.target.removeEventListener(b.De,b.Nf,b.Qe);K.ve.splice(a,1)}function Ib(){if(navigator.userActivation?navigator.userActivation.isActive:K.Bf&&K.hg.rf){var a=K.Ge;K.Ge=[];for(var b of a)b.Gf(...b.Lf)}}function Jb(a){if(!a.target)return-4;if(a.Re)a.Nf=function(c){++K.Bf;K.hg=a;Ib();a.Ue(c);Ib();--K.Bf},a.target.addEventListener(a.De,a.Nf,a.Qe),K.ve.push(a);else for(var b=0;b<K.ve.length;++b)K.ve[b].target==a.target&&K.ve[b].De==a.De&&Hb(b--);return 0}
var K={Cg:0,yf:0,Yg:0,kf:0,nh:0,If:0,Tg:0,Pg:0,dh:0,Og:0,xf:0,eh:0,mh:0,Hf:0,Zg(a,b,c){m.set(m.subarray(b,b+c),a)},gh(){for(;K.ve.length;)Hb(K.ve.length-1);K.Ge=[]},Bf:0,Ge:[],Mg(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var n in f)if(f[n]!=g[n])return!1;return!0}for(var e of K.Ge)if(e.Gf==a&&d(e.Lf,c))return;K.Ge.push({Gf:a,Wf:b,Lf:c});K.Ge.sort((f,g)=>f.Wf<g.Wf)},ih(a){K.Ge=K.Ge.filter(b=>b.Gf!=a)},ve:[],hh:(a,b)=>{for(var c=0;c<K.ve.length;++c)K.ve[c].target!=a||b&&b!=K.ve[c].De||
Hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Kb=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)m[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];m[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;
C(b.id,p,a+1112,64);C(b.mapping,p,a+1176,64)},L,Lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Mb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),
a.isVertexArray=c=>b.isVertexArrayOES(c))},Nb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ob=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Pb=1,Qb=[],M=[],Rb=[],Sb=[],Tb=[],N=[],Ub=[],Vb=[],O=[],Wb={},Yb=4,Zb=0,$b=a=>{for(var b=Pb++,c=a.length;c<b;c++)a[c]=null;return b},ac=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=L[c](),g=f&&$b(d);f?(f.name=g,d[g]=f):P||=1282;t[b+4*e>>2]=g}},cc=(a,b)=>{a.Ne||(a.Ne=a.getContext,a.getContext=function(d,e){e=a.Ne(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?bc(c,b):0},bc=(a,b)=>{var c=
$b(Vb),d={handle:c,attributes:b,version:b.rg,qf:a};a.canvas&&(a.canvas.yg=d);Vb[c]=d;("undefined"==typeof b.jg||b.jg)&&dc(d);return c},dc=a=>{a||=ec;if(!a.mg){a.mg=!0;var b=a.qf;b.$g=b.getExtension("WEBGL_multi_draw");b.lg=b.getExtension("EXT_polygon_offset_clamp");b.kg=b.getExtension("EXT_clip_control");b.xg=b.getExtension("WEBGL_polygon_mode");Lb(b);Mb(b);Nb(b);b.Ce=b.getExtension("EXT_disjoint_timer_query");Ob(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},
fc={},P,ec,gc=a=>L.activeTexture(a),hc=(a,b)=>{L.attachShader(M[a],N[b])},ic=(a,b,c)=>{L.bindAttribLocation(M[a],b,c?z(p,c):"")},jc=(a,b)=>{L.bindBuffer(a,Qb[b])},kc=(a,b)=>{L.bindTexture(a,Tb[b])},lc=(a,b)=>L.blendFunc(a,b),mc=(a,b,c,d)=>{L.bufferData(a,c?p.subarray(c,c+b):b,d)},nc=(a,b,c,d)=>{L.bufferSubData(a,b,p.subarray(d,d+c))},oc=a=>L.clear(a),pc=(a,b,c,d)=>L.clearColor(a,b,c,d),qc=a=>L.clearDepth(a),rc=a=>{L.compileShader(N[a])},sc=(a,b,c,d,e,f,g,n)=>{L.compressedTexImage2D(a,b,c,d,e,f,p.subarray(n,
n+g))},tc=()=>{var a=$b(M),b=L.createProgram();b.name=a;b.ff=b.df=b.ef=0;b.Jf=1;M[a]=b;return a},uc=a=>{var b=$b(N);N[b]=L.createShader(a);return b},vc=a=>L.cullFace(a),wc=a=>{if(a){var b=M[a];b?(L.deleteProgram(b),b.name=0,M[a]=null):P||=1281}},xc=a=>L.depthFunc(a),yc=a=>L.disable(a),zc=(a,b,c)=>{L.drawArrays(a,b,c)},Ac=[],Bc=(a,b,c,d)=>{L.drawElements(a,b,c,d)},Cc=a=>L.enable(a),Dc=a=>{L.enableVertexAttribArray(a)},Ec=a=>L.frontFace(a),Fc=(a,b)=>{ac(a,b,"createBuffer",Qb)},Gc=(a,b)=>{ac(a,b,"createTexture",
Tb)},Hc=(a,b,c,d,e,f,g,n)=>{b=M[b];if(a=L[a](b,c))d=n&&C(a.name,p,n,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},Ic=(a,b)=>L.getAttribLocation(M[a],b?z(p,b):""),Jc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);
return}}break;default:P||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:m[b]=d?1:0}}else P||=1281},Kc=(a,b)=>Jc(a,b,2),Lc=(a,b,c,d)=>{a=L.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,p,d,b):0;c&&(t[c>>2]=b)},Mc=(a,b,c)=>{if(c)if(a>=Pb)P||=1281;else if(a=M[a],35716==b)a=L.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.ff){var d=L.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ff=Math.max(a.ff,L.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.ff}else if(35722==b){if(!a.df)for(d=L.getProgramParameter(a,35721),b=0;b<d;++b)a.df=Math.max(a.df,L.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.df}else if(35381==b){if(!a.ef)for(d=L.getProgramParameter(a,35382),b=0;b<d;++b)a.ef=Math.max(a.ef,L.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.ef}else t[c>>
2]=L.getProgramParameter(a,b);else P||=1281},Nc=(a,b,c)=>{if(c){a=L.Ce.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else P||=1281},Oc=(a,b,c)=>{if(c){a=L.Ce.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else P||=1281},Pc=(a,b,c,d)=>{a=L.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,p,d,b):0;c&&(t[c>>2]=b)},Qc=(a,b,c)=>{c?35716==b?(a=L.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),
t[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(N[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=L.getShaderParameter(N[a],b):P||=1281},Rc=a=>{var b=Ha(a)+1,c=Q(b);c&&C(a,p,c,b);return c},Sc=()=>{var a=Ob(L);return a=a.concat(a.map(b=>"GL_"+b))},Tc=a=>{var b=Wb[a];if(!b){switch(a){case 7939:b=Rc(Sc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||(P||=1280);b=b?Rc(b):0;break;case 7938:b=Rc(`OpenGL ES 2.0 (${L.getParameter(7938)})`);break;case 35724:b=L.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Rc(b);break;default:P||=1280}Wb[a]=b}return b},Uc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Vc=a=>{var b=a.Xe,c=a.bg,d;if(!b){a.Xe=b={};a.ag={};var e=L.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=L.getActiveUniform(a,d);var g=f.name;f=f.size;var n=Uc(g);n=0<n?g.slice(0,n):g;var r=a.Jf;a.Jf+=f;c[n]=[f,r];for(g=0;g<f;++g)b[r]=g,a.ag[r++]=n}}},Wc=(a,b)=>{b=
b?z(p,b):"";if(a=M[a]){Vc(a);var c=a.Xe,d=0,e=b,f=Uc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.bg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else P||=1281;return-1},R=a=>{var b=L.ig;if(b){var c=b.Xe[a];"number"==typeof c&&(b.Xe[a]=c=L.getUniformLocation(b,b.ag[a]+(0<c?`[${c}]`:"")));return c}P||=1282},Xc=(a,b,c,d)=>{if(c)if(a=M[a],Vc(a),a=L.getUniform(a,R(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=
0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else P||=1281},Yc=(a,b,c,d)=>{if(c)if(a=L.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else P||=1281},Zc=a=>{a=M[a];L.linkProgram(a);a.Xe=0;a.bg={}},
$c=(a,b)=>{3317==a?Yb=b:3314==a&&(Zb=b);L.pixelStorei(a,b)},ad=(a,b,c,d,e)=>{a-=5120;a=1==a?p:4==a?t:6==a?v:5==a||28922==a?u:ia;b=d*((Zb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Yb-1&-Yb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},bd=(a,b,c,d,e,f,g)=>{(g=ad(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):P||=1280},cd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=u[c+4*f>>2])?z(p,g,d?u[d+4*f>>2]:void 0):"";e+=g}L.shaderSource(N[a],
e)},dd=(a,b,c,d,e,f,g,n,r)=>{r=r?ad(n,g,d,e,r):null;L.texImage2D(a,b,c,d,e,f,g,n,r)},ed=(a,b,c)=>L.texParameterf(a,b,c),fd=(a,b,c)=>L.texParameteri(a,b,c),gd=[],hd=(a,b)=>{L.uniform1i(R(a),b)},jd=[],kd=(a,b,c,d,e)=>{L.uniform4f(R(a),b,c,d,e)},ld=(a,b,c,d)=>{if(18>=b){var e=gd[16*b],f=v;d>>=2;b*=16;for(var g=0;g<b;g+=16){var n=d+g;e[g]=f[n];e[g+1]=f[n+1];e[g+2]=f[n+2];e[g+3]=f[n+3];e[g+4]=f[n+4];e[g+5]=f[n+5];e[g+6]=f[n+6];e[g+7]=f[n+7];e[g+8]=f[n+8];e[g+9]=f[n+9];e[g+10]=f[n+10];e[g+11]=f[n+11];e[g+
12]=f[n+12];e[g+13]=f[n+13];e[g+14]=f[n+14];e[g+15]=f[n+15]}}else e=v.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(R(a),!!c,e)},md=a=>{a=M[a];L.useProgram(a);L.ig=a},nd=(a,b,c,d,e,f)=>{L.vertexAttribPointer(a,b,c,!!d,e,f)},od=(a,b,c,d)=>L.viewport(a,b,c,d),pd=()=>{try{if(navigator.getGamepads)return(K.cf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},rd=(a,b,c,d)=>{K.kf||(K.kf=Q(64));a=Fb(a);return Jb({target:a,rf:!0,De:"click",Re:d,Ue:(e=event)=>{var f=a,g=K.kf;x[g>>3]=
e.timeStamp;var n=g>>2;t[n+2]=e.screenX;t[n+3]=e.screenY;t[n+4]=e.clientX;t[n+5]=e.clientY;m[g+24]=e.ctrlKey;m[g+25]=e.shiftKey;m[g+26]=e.altKey;m[g+27]=e.metaKey;ha[2*n+14]=e.button;ha[2*n+15]=e.buttons;t[n+8]=e.movementX;t[n+9]=e.movementY;f=Gb(f);t[n+10]=e.clientX-(f.left|0);t[n+11]=e.clientY-(f.top|0);qd(d,4,K.kf,b)&&e.preventDefault()},Qe:c})};
function sd(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var td=(a,b,c,d,e)=>{K.xf||(K.xf=Q(276));return Jb({target:a,De:e,Re:d,Ue:(f=event)=>{var g=K.xf,n=sd(),r=!!n;m[g]=r;m[g+1]=K.fullscreenEnabled();var q=r?n:K.ug,A=q?.id||"";C(q?q==window?"#window":q==screen?"#screen":q?.nodeName||"":"",p,g+2,128);C(A,p,g+130,128);t[g+260>>2]=q?q.clientWidth:0;t[g+264>>2]=q?q.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;r&&(K.ug=n);qd(d,19,g,b)&&f.preventDefault()},Qe:c})},ud=(a,b,c,d,e)=>{K.yf||(K.yf=Q(1240));b={target:Fb(2),rf:!0,De:e,Re:c,Ue:(f=
event)=>{var g=K.yf;Kb(g,f.gamepad);qd(c,d,g,a)&&f.preventDefault()},Qe:b};return Jb(b)},vd=(a,b,c,d)=>{K.If||(K.If=Q(36));a=Fb(a);return Jb({target:a,De:"resize",Re:d,Ue:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=K.If;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;qd(d,10,g,b)&&e.preventDefault()}}},Qe:c})},wd=(a,b,c,d,e,f)=>{K.Hf||
(K.Hf=Q(1552));a=Fb(a);return Jb({target:a,rf:"touchstart"==f||"touchend"==f,De:f,Re:d,Ue:g=>{var n={},r=g.touches;for(var q of r)q.Qf=q.Vf=0,n[q.identifier]=q;for(var A of g.changedTouches)A.Qf=1,n[A.identifier]=A;for(var w of g.targetTouches)n[w.identifier].Vf=1;r=K.Hf;x[r>>3]=g.timeStamp;m[r+12]=g.ctrlKey;m[r+13]=g.shiftKey;m[r+14]=g.altKey;m[r+15]=g.metaKey;q=r+16;A=Gb(a);w=0;for(let B of Object.values(n))if(n=q>>2,t[n]=B.identifier,t[n+1]=B.screenX,t[n+2]=B.screenY,t[n+3]=B.clientX,t[n+4]=B.clientY,
t[n+5]=B.pageX,t[n+6]=B.pageY,m[q+28]=B.Qf,m[q+29]=B.Vf,t[n+8]=B.clientX-(A.left|0),t[n+9]=B.clientY-(A.top|0),q+=48,31<++w)break;t[r+8>>2]=w;qd(d,e,r,b)&&g.preventDefault()},Qe:c})},xd=(a,b)=>setTimeout(()=>{Db(a)},b),S=!1,yd=!1,zd=[];
function Ad(){function a(){yd=document.pointerLockElement===h.canvas}if(!Bd){Bd=!0;Ua.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Cd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Cd(d)}));var f=URL.createObjectURL(e);return new Promise((g,n)=>{var r=new Image;r.onload=()=>{var q=document.createElement("canvas");q.width=r.width;q.height=r.height;q.getContext("2d").drawImage(r,
0,0);URL.revokeObjectURL(f);g(c)};r.onerror=()=>{k(`Image ${f} could not be decoded`);n()};r.src=f})}});Ua.push({canHandle:function(c){return!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,n=URL.createObjectURL(new Blob([c],{type:Cd(d)})),r=new Audio;r.addEventListener("canplaythrough",()=>f(r),!1);r.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",A=0,w=0,B=0;B<c.length;B++)for(A=A<<8|c[B],w+=8;6<=w;){var va=A>>w-6&63;w-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[va]}2==w?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&3)<<4],q+="=="):4==w&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&15)<<2],q+="=");r.src="data:audio/x-"+d.slice(-3)+";base64,"+q;f(r)}};r.src=n;xd(()=>{f(r)},1E4)})}});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",
a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!yd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Dd(a){var b={antialias:1<T[135181],depth:0<T[135173],stencil:0<T[135174],alpha:0<T[135172]};if(!h.ctx||a!=h.canvas){var c,d={antialias:!1,alpha:!1,rg:1};if(b)for(var e in b)d[e]=b[e];if("undefined"!=typeof fc&&(c=cc(a,d)))var f=Vb[c].qf;f&&(h.ctx=f,ec=Vb[c],h.ctx=L=ec?.qf,zd.forEach(g=>g()),Ad())}}var Ed=!1,Fd=void 0,U=void 0;
function Gd(a,b){function c(){S=!1;var f=d.parentNode;sd()===f?(d.exitFullscreen=Hd,Fd&&d.requestPointerLock(),S=!0,U?Id():V(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),U?Jd():V(d));h.onFullScreen?.(S);h.onFullscreen?.(S)}Fd=a;U=b;"undefined"==typeof Fd&&(Fd=!0);"undefined"==typeof U&&(U=!1);var d=h.canvas;Ed||(Ed=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),
document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Hd(){if(!S)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}function Cd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var Kd=0,Ld=0,Md=0,Nd=0;
function Od(a,b){var c=h.canvas,d=c.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+d.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+d.top;a*=c.width/d.width;b*=c.height/d.height;return{x:a,y:b}}function Pd(a,b){const {x:c,y:d}=Od(a,b);Md=c-Kd;Nd=d-Ld;Kd=c;Ld=d}
function Qd(a){yd?("mousemove"!=a.type&&"mozMovementX"in a?Md=Nd=0:(Md=a.movementX||a.mozMovementX||a.webkitMovementX||0,Nd=a.movementY||a.mozMovementY||a.webkitMovementY||0),Kd+=Md,Ld+=Nd):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.kh,void 0!==a&&Od(a.pageX,a.pageY)):Pd(a.pageX,a.pageY)}var Rd=[];function Sd(){var a=h.canvas;Rd.forEach(b=>b(a.width,a.height))}function Id(){"undefined"!=typeof SDL&&(t[SDL.screen>>2]=u[SDL.screen>>2]|8388608);V(h.canvas);Sd()}
function Jd(){"undefined"!=typeof SDL&&(t[SDL.screen>>2]=u[SDL.screen>>2]&-8388609);V(h.canvas);Sd()}
function V(a,b,c){b&&c?(a.Kf=b,a.Af=c):(b=a.Kf,c=a.Af);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if(sd()===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}U?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=
c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Bd;
function Td(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.af=!1;this.$f=this.Zf=0;this.width=b;this.height=c;this.wf=d;this.vf=e;this.Ff=b;this.Ef=c;this.title=f;this.attributes={...T};this.buttons=0;this.keys=[];this.tf=[];this.vg=0;this.title=null;this.Ye=this.bf=this.Te=this.mf=this.Oe=this.Se=this.jf=this.dg=this.Of=this.fg=this.eg=this.pf=0}
var ce=(a,b)=>{Ud=a;Vd=b;if(Wd)if(Xd||=!0,0==a)Yd=function(){setTimeout(Zd,Math.max(0,$d+b-performance.now())|0)};else if(1==a)Yd=function(){ae(Zd)};else if(2==a){if(!be)if(globalThis.setImmediate)be=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);be=d=>{c.push(d);postMessage("setimmediate","*")}}Yd=function(){be(Zd)}}},ke=a=>{function b(){return c<de?(Cb(),!1):!0}Wd=a;var c=de;Xd=!1;Zd=function(){if(!l)if(0<
ee.length){var d=ee.shift();d.Ug(d.Ag);if(fe){var e=fe,f=0==e%1?e-1:Math.floor(e);fe=d.Lg?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=fe??0,f=ge.Sg??0,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(Zd,0)}else if(b())if(he=he+1|0,1==Ud&&1<Vd&&0!=he%Vd)Yd();else{0==Ud&&($d=performance.now());a:if(!l){for(d of ie)if(!1===d())break a;Db(a);for(e of je)e()}b()&&Yd()}}},Xd=!1,Yd=null,de=0,Wd=null,Ud=0,Vd=0,he=0,
ee=[],ie=[],je=[];function le(){Yd=null;de++}function me(){de++;var a=Ud,b=Vd,c=Wd;Wd=null;ke(c);ce(a,b);Yd()}var ne=0;function ae(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ne)ne=b+1E3/60;else for(;b+2>=ne;)ne+=1E3/60;setTimeout(a,Math.max(ne-b,0))}}
var ge={},$d,Zd,be,fe,X=a=>0>=a||!W?null:W[a-1],oe=0,Y=null,pe=null,W=null,qe=null,re=null,T=null,se=null,te={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},ue=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;
case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;
case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;
case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;
case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;
case 93:return 348;default:return-1}},ve=()=>{var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},we=a=>{Y&&Y.Ye&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii(Y.Ye,Y.id,a))},ye=(a,b)=>{if(Y){var c=ue(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.tf[a]=b;Y.bf&&(d&&(b=2),xe(Y.bf,Y.id,c,a,b,ve()))}}},Ae=()=>{ze()},Be=()=>{ze()},Ce=a=>{ye(a.keyCode,1);"Backspace"!=a.key&&"Tab"!=a.key||a.preventDefault()},De=a=>{ye(a.keyCode,
0)},Ee=()=>{if(Y)for(var a=0;a<Y.tf.length;++a)Y.tf[a]&&ye(a,0)},Ge=a=>{if(Y){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(se===c.identifier){Pd(c.pageX,c.pageY);b=!0;break}if(!b)return}else Qd(a);a.target==h.canvas&&Y.Se&&Y.Se&&Fe(Y.Se,Y.id,Kd,Ld)}},He=a=>{Y&&a.target==h.canvas&&Y.Oe&&dynCall_vii(Y.Oe,Y.id,1)},Ie=a=>{Y&&a.target==h.canvas&&Y.Oe&&dynCall_vii(Y.Oe,Y.id,0)},Ke=(a,b)=>{if(Y&&a.target==h.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||
"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===se&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],se=d.identifier,Pd(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(se===e.identifier){se=null;d=!0;break}if(!d)return}else Qd(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else Y.buttons&=~(1<<c);Y.jf&&Je(Y.jf,Y.id,c,b,ve())}},Oe=a=>{Y&&Ke(a,1)},Pe=a=>{Y&&Ke(a,
0)},Qe=a=>{var b=0;switch(a.type){case "DOMMouseScroll":b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:y("unrecognized mouse wheel delta mode: "+a.deltaMode)}break;default:y("unrecognized mouse wheel event: "+a.type)}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);Y&&Y.mf&&a.target==h.canvas&&(Fe(Y.mf,Y.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b),a.preventDefault())},Se=
(a,b,c,d)=>{if(Y){var e=!1;sd()?Y.af||(e=a!=screen.width||b!=screen.height,Y.Zf=Y.x,Y.$f=Y.y,Y.Ff=Y.width,Y.Ef=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.af=!0):1==Y.af&&(e=a!=Y.Ff||b!=Y.Ef,Y.x=Y.Zf,Y.y=Y.$f,Y.width=Y.Ff,Y.height=Y.Ef,Y.af=!1);if(e)V(h.canvas,Y.width,Y.height),Sd();else if(Y.width!=a||Y.height!=b||Y.wf!=c||Y.vf!=d)Y.width=a,Y.height=b,Y.wf=c,Y.vf=d,Y&&Y.pf&&Re(Y.pf,Y.id,Y.width,Y.height),Y&&Y.Of&&Re(Y.Of,Y.id,Y.wf,Y.vf)}},Te={},Ue=[],Ve=null,ze=()=>{if(he!==
Ve||!he){Ue=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];Ve=he;for(var a=0;a<Ue.length;++a){var b=Ue[a];if(b){Te[a]||(da("glfw joystick connected:",a),Te[a]={id:Rc(b.id),Eg:b.buttons.length,Bg:b.axes.length,buttons:Q(b.buttons.length),axes:Q(4*b.axes.length)});for(var c=Te[a],d=0;d<b.buttons.length;++d)m[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)v[c.axes+4*d>>2]=b.axes[d]}else Te[a]&&(da("glfw joystick disconnected",a),We(Te[a].id),We(Te[a].buttons),
We(Te[a].axes),delete Te[a])}}},Xe=a=>{function b(n){var r="/.glfw_dropped_files/"+n.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=w=>{if(2!=q.readyState)++f,da("failed to read dropped file: "+n.name+": "+q.error);else{w=new Uint8Array(w.target.result);var B={};B.flags=B.flags||577;var va=pb(r,B.flags,B.mode);"string"==typeof w&&(w=new Uint8Array(Ia(w)));ArrayBuffer.isView(w)?tb(va,w,0,w.byteLength,void 0,B.Kg):y("Unsupported data type");rb(va);if(++f===e){Re(Y.Te,Y.id,e,c);for(w=0;w<d.length;++w)We(d[w]);
We(c)}}};q.readAsArrayBuffer(n);var A=Rc(r);d.push(A);u[c+4*g>>2]=A}if(Y&&Y.Te&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Q(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;ub();for(var g=0;g<e;++g)b(a.dataTransfer.files[g]);return!1}},Ye=a=>{if(Y&&Y.Te)return a.preventDefault(),!1};
function Ze(a,b){function c(){S=!1;var f=d.parentNode;sd()===f?(d.exitFullscreen=Hd,Fd&&d.requestPointerLock(),S=!0,U?Id():(V(d),Sd())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),U?Jd():(V(d),Sd()));h.onFullScreen?.(S);h.onFullscreen?.(S)}Fd=a;U=b;"undefined"==typeof Fd&&(Fd=!0);"undefined"==typeof U&&(U=!1);var d=h.canvas;Ed||(Ed=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",
c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function $e(a,b,c){var d=af()?pe:1;b&&c?(a.Kf=b,a.Af=c):(b=a.Kf,c=a.Af);var e=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(e/f<h.forcedAspectRatio?e=Math.round(f*h.forcedAspectRatio):f=Math.round(e/h.forcedAspectRatio));if(sd()===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}U&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(af()?(a.style.setProperty("width",
b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}function bf(a,b){const c=h.canvas.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;!af()&&Y&&(a*=Y.width/c.width,b*=Y.height/c.height);return{x:a,y:b}}function cf(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}
function af(){return Y?0<Y.attributes[139276]:!1}function df(){Y&&(V(h.canvas,Y.width,Y.height),Sd())}function ef(){pe=cf();Y&&Y.dg&&ff(Y.dg,Y.id,pe,pe);df()}var gf=a=>{try{a()}catch(b){y(b)}};function hf(a){var b=(...c)=>{jf.push(a);try{return a(...c)}finally{l||(jf.pop(),kf&&1===lf&&0===jf.length&&(lf=0,gf(mf),"undefined"!=typeof Fibers&&Fibers.lh()))}};nf.set(a,b);return b}var lf=0,kf=null,of=0,jf=[],pf=new Map,qf=new Map,nf=new Map,rf=0,sf=null,tf=[];
function uf(){var a=Q(4108),b=a+12;u[a>>2]=b;u[a+4>>2]=b+4096;b=jf[0];if(!pf.has(b)){var c=rf++;pf.set(b,c);qf.set(c,b)}b=pf.get(b);t[a+8>>2]=b;return a}function vf(){var a=qf.get(t[kf+8>>2]);return nf.get(a)()}
function wf(a){if(!l){if(0===lf){var b=!1,c=!1;a((d=0)=>{if(!l&&(of=d,b=!0,c)){lf=2;gf(()=>xf(kf));"undefined"!=typeof ge&&Wd&&me();d=!1;try{var e=vf()}catch(n){e=n,d=!0}var f=!1;if(!kf){var g=sf;g&&(sf=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(lf=1,kf=uf(),"undefined"!=typeof ge&&Wd&&le(),gf(()=>yf(kf)))}else 2===lf?(lf=0,gf(zf),We(kf),kf=null,tf.forEach(Db)):y(`invalid state: ${lf}`);return of}}F=Array(4096);lb(E,"/");H("/tmp");H("/home");H("/home/web_user");
(function(){H("/dev");La(259,{read:()=>0,write:(d,e,f,g)=>g,ye:()=>0});nb("/dev/null",259);Ka(1280,Na);Ka(1536,Oa);nb("/dev/tty",1280);nb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ea(a),b=a.byteLength);return a[--b]};vb("random",c);vb("urandom",c);H("/dev/shm");H("/dev/shm/tmp")})();
(function(){H("/proc");var a=H("/proc/self");H("/proc/self/fd");lb({Ee(){var b=Qa(a,"fd",16895,73);b.le={ye:E.le.ye};b.pe={Ve(c,d){c=+d;var e=G(c);c={parent:null,Ee:{Tf:"fake"},pe:{We:()=>e.path},id:c+1};return c.parent=c},Df(){return Array.from(Xa.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();for(let a=0;32>a;++a)Ac.push(Array(a));for(var Af=new Float32Array(288),Z=0;288>=Z;++Z)gd[Z]=Af.subarray(0,Z);var Bf=new Int32Array(288);
for(Z=0;288>=Z;++Z)jd[Z]=Bf.subarray(0,Z);h.requestAnimationFrame=ae;h.pauseMainLoop=le;h.resumeMainLoop=me;h.preMainLoop&&ie.push(h.preMainLoop);h.postMainLoop&&je.push(h.postMainLoop);h.noExitRuntime&&(ya=h.noExitRuntime);h.preloadPlugins&&(Ua=h.preloadPlugins);h.print&&(da=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(ea=h.wasmBinary);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var Cf,Q,We,Df,dynCall_vii,Re,xe,Je,Fe,qd,dynCall_vi,dynCall_v,dynCall_iii,ff,yf,mf,xf,zf,la,Ef={wa:function(){return window.innerHeight},xa:function(){return window.innerWidth},l:(a,b,c,d)=>y(`Assertion failed: ${a?z(p,a):""}, at: `+[b?b?z(p,b):"":"unknown filename",c,d?d?z(p,d):"":"unknown function"]),ab:function(a,b,c){try{b=b?z(p,b):"";b=wb(a,b);if(c&-8)return-28;var d=db(b,{Ze:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&fb(d,a)?-2:0}catch(e){if("undefined"==
typeof I||"ErrnoError"!==e.name)throw e;return-e.te}},z:function(a,b,c){xb=c;try{var d=G(a);switch(b){case 0:var e=J();if(0>e)break;for(;Xa[e];)e++;return jb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=J(),d.flags|=e,0;case 12:return e=J(),ha[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return-f.te}},Ua:function(a,b){try{if(0===b)return-28;var c=Ha("/")+1;if(b<c)return-68;C("/",p,a,b);return c}catch(d){if("undefined"==
typeof I||"ErrnoError"!==d.name)throw d;return-d.te}},Ya:function(a,b,c){xb=c;try{var d=G(a);switch(b){case 21509:return d.qe?0:-59;case 21505:if(!d.qe)return-59;if(d.qe.Fe.og){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=J();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.qe?0:-59;case 21506:case 21507:case 21508:if(!d.qe)return-59;if(d.qe.Fe.pg)for(e=J(),a=[],
f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.qe)return-59;e=J();return t[e>>2]=0;case 21520:return d.qe?-28:-59;case 21537:case 21531:e=J();if(!d.le.ng)throw new D(59);return d.le.ng(d,b,e);case 21523:if(!d.qe)return-59;d.qe.Fe.qg&&(f=[24,80],e=J(),ha[e>>1]=f[0],ha[e+2>>1]=f[1]);return 0;case 21524:return d.qe?0:-59;case 21515:return d.qe?0:-59;default:return-28}}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return-g.te}},Za:function(a,b,c,d){xb=d;try{b=b?z(p,b):"";
b=wb(a,b);var e=d?J():0;return pb(b,c,e).fd}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return-f.te}},Qa:()=>y(""),Pa:()=>{ya=!1;yb=0},Ra:(a,b)=>{zb[a]&&(clearTimeout(zb[a].id),delete zb[a]);if(!b)return 0;var c=setTimeout(()=>{delete zb[a];Db(()=>Df(a,performance.now()))},b);zb[a]={id:c,jh:b};return 0},$a:function(a,b,c){if(!(0<=a&&3>=a))return 28;ja[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},_a:()=>Date.now(),Q:(a,b,c)=>{a=Fb(a);if(!a)return-4;
a=Gb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},ra:(a,b)=>{if(0>a||a>=K.cf.length)return-5;if(!K.cf[a])return-7;Kb(b,K.cf[a]);return 0},m:()=>performance.now(),sa:()=>K.cf.length,Td:gc,Sd:hc,L:(a,b)=>{L.Ce.beginQueryEXT(a,O[b])},Qd:ic,Pd:jc,Od:(a,b)=>{L.bindFramebuffer(a,Rb[b])},Nd:(a,b)=>{L.bindRenderbuffer(a,Sb[b])},Md:kc,$d:a=>{L.bindVertexArray(Ub[a])},Ld:(a,b,c,d)=>L.blendColor(a,b,c,d),Kd:a=>L.blendEquation(a),Jd:(a,b)=>L.blendEquationSeparate(a,b),Id:lc,Hd:(a,b,c,d)=>L.blendFuncSeparate(a,
b,c,d),Fd:mc,Ed:nc,Dd:a=>L.checkFramebufferStatus(a),Cd:oc,Bd:pc,Ad:qc,zd:a=>L.clearStencil(a),cb:(a,b)=>{L.kg.clipControlEXT(a,b)},yd:(a,b,c,d)=>{L.colorMask(!!a,!!b,!!c,!!d)},xd:rc,wd:sc,vd:(a,b,c,d,e,f,g,n,r)=>{L.compressedTexSubImage2D(a,b,c,d,e,f,g,p.subarray(r,r+n))},ud:(a,b,c,d,e,f,g,n)=>L.copyTexImage2D(a,b,c,d,e,f,g,n),td:(a,b,c,d,e,f,g,n)=>L.copyTexSubImage2D(a,b,c,d,e,f,g,n),sd:tc,rd:uc,qd:vc,pd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Qb[d];e&&(L.deleteBuffer(e),e.name=0,Qb[d]=
null)}},od:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Rb[d];e&&(L.deleteFramebuffer(e),e.name=0,Rb[d]=null)}},nd:wc,N:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=O[d];e&&(L.Ce.deleteQueryEXT(e),O[d]=null)}},md:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Sb[d];e&&(L.deleteRenderbuffer(e),e.name=0,Sb[d]=null)}},ld:a=>{if(a){var b=N[a];b?(L.deleteShader(b),N[a]=null):P||=1281}},kd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Tb[d];e&&(L.deleteTexture(e),e.name=0,Tb[d]=null)}},_d:(a,
b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];L.deleteVertexArray(Ub[d]);Ub[d]=null}},jd:xc,id:a=>{L.depthMask(!!a)},hd:(a,b)=>L.depthRange(a,b),gd:(a,b)=>{L.detachShader(M[a],N[b])},fd:yc,ed:a=>{L.disableVertexAttribArray(a)},dd:zc,Wd:(a,b,c,d)=>{L.drawArraysInstanced(a,b,c,d)},Xd:(a,b)=>{for(var c=Ac[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];L.drawBuffers(c)},cd:Bc,Vd:(a,b,c,d,e)=>{L.drawElementsInstanced(a,b,c,d,e)},bd:Cc,ad:Dc,K:a=>{L.Ce.endQueryEXT(a)},$c:()=>L.finish(),_c:()=>L.flush(),Zc:(a,b,c,d)=>{L.framebufferRenderbuffer(a,
b,c,Sb[d])},Yc:(a,b,c,d,e)=>{L.framebufferTexture2D(a,b,c,Tb[d],e)},Xc:Ec,Wc:Fc,Uc:(a,b)=>{ac(a,b,"createFramebuffer",Rb)},O:(a,b)=>{for(var c=0;c<a;c++){var d=L.Ce.createQueryEXT();if(!d){for(P||=1282;c<a;)t[b+4*c++>>2]=0;break}var e=$b(O);d.name=e;O[e]=d;t[b+4*c>>2]=e}},Sc:(a,b)=>{ac(a,b,"createRenderbuffer",Sb)},Rc:Gc,Zd:(a,b)=>{ac(a,b,"createVertexArray",Ub)},Vc:a=>L.generateMipmap(a),Qc:(a,b,c,d,e,f,g)=>Hc("getActiveAttrib",a,b,c,d,e,f,g),Pc:(a,b,c,d,e,f,g)=>Hc("getActiveUniform",a,b,c,d,e,f,
g),Oc:(a,b,c,d)=>{a=L.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=N.indexOf(a[b])},Nc:Ic,Mc:(a,b)=>Jc(a,b,4),Lc:(a,b,c)=>{c?t[c>>2]=L.getBufferParameter(a,b):P||=1281},Kc:()=>{var a=L.getError()||P;P=0;return a},Jc:Kc,Hc:(a,b,c,d)=>{a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Gc:(a,b)=>Jc(a,b,0),Ec:Lc,Fc:Mc,F:Nc,H:Oc,E:Nc,G:Oc,I:(a,b,c)=>{c?t[c>>2]=L.Ce.getQueryEXT(a,b):
P||=1281},Dc:(a,b,c)=>{c?t[c>>2]=L.getRenderbufferParameter(a,b):P||=1281},Bc:Pc,Ac:(a,b,c,d)=>{a=L.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},zc:(a,b,c,d)=>{if(a=L.getShaderSource(N[a]))b=0<b&&d?C(a,p,d,b):0,c&&(t[c>>2]=b)},Cc:Qc,yc:Tc,wc:(a,b,c)=>{c?v[c>>2]=L.getTexParameter(a,b):P||=1281},vc:(a,b,c)=>{c?t[c>>2]=L.getTexParameter(a,b):P||=1281},sc:Wc,uc:(a,b,c)=>{Xc(a,b,c,2)},tc:(a,b,c)=>{Xc(a,b,c,0)},pc:(a,b,c)=>{c?t[c>>2]=L.getVertexAttribOffset(a,
b):P||=1281},rc:(a,b,c)=>{Yc(a,b,c,2)},qc:(a,b,c)=>{Yc(a,b,c,5)},oc:(a,b)=>L.hint(a,b),nc:a=>(a=Qb[a])?L.isBuffer(a):0,mc:a=>L.isEnabled(a),lc:a=>(a=Rb[a])?L.isFramebuffer(a):0,kc:a=>(a=M[a])?L.isProgram(a):0,M:a=>(a=O[a])?L.Ce.isQueryEXT(a):0,jc:a=>(a=Sb[a])?L.isRenderbuffer(a):0,ic:a=>(a=N[a])?L.isShader(a):0,hc:a=>(a=Tb[a])?L.isTexture(a):0,Yd:a=>(a=Ub[a])?L.isVertexArray(a):0,gc:a=>L.lineWidth(a),fc:Zc,ec:$c,bb:(a,b)=>{L.xg.polygonModeWEBGL(a,b)},dc:(a,b)=>L.polygonOffset(a,b),db:(a,b,c)=>{L.lg.polygonOffsetClampEXT(a,
b,c)},J:(a,b)=>{L.Ce.queryCounterEXT(O[a],b)},cc:bd,bc:()=>{},ac:(a,b,c,d)=>L.renderbufferStorage(a,b,c,d),$b:(a,b)=>{L.sampleCoverage(a,!!b)},_b:(a,b,c,d)=>L.scissor(a,b,c,d),Zb:()=>{P||=1280},Yb:cd,Xb:(a,b,c)=>L.stencilFunc(a,b,c),Wb:(a,b,c,d)=>L.stencilFuncSeparate(a,b,c,d),Vb:a=>L.stencilMask(a),Tb:(a,b)=>L.stencilMaskSeparate(a,b),Sb:(a,b,c)=>L.stencilOp(a,b,c),Rb:(a,b,c,d)=>L.stencilOpSeparate(a,b,c,d),Qb:dd,Pb:ed,Ob:(a,b,c)=>{L.texParameterf(a,b,v[c>>2])},Nb:fd,Mb:(a,b,c)=>{L.texParameteri(a,
b,t[c>>2])},Lb:(a,b,c,d,e,f,g,n,r)=>{r=r?ad(n,g,e,f,r):null;L.texSubImage2D(a,b,c,d,e,f,g,n,r)},Kb:(a,b)=>{L.uniform1f(R(a),b)},Jb:(a,b,c)=>{if(288>=b)for(var d=gd[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);L.uniform1fv(R(a),d)},Ib:hd,Hb:(a,b,c)=>{if(288>=b)for(var d=jd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);L.uniform1iv(R(a),d)},Gb:(a,b,c)=>{L.uniform2f(R(a),b,c)},Fb:(a,b,c)=>{if(144>=b){b*=2;for(var d=gd[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+
(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);L.uniform2fv(R(a),d)},Eb:(a,b,c)=>{L.uniform2i(R(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=jd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+8*b>>2);L.uniform2iv(R(a),d)},Cb:(a,b,c,d)=>{L.uniform3f(R(a),b,c,d)},Bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=gd[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);L.uniform3fv(R(a),d)},Ab:(a,b,c,d)=>{L.uniform3i(R(a),
b,c,d)},zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=jd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);L.uniform3iv(R(a),d)},yb:kd,xb:(a,b,c)=>{if(72>=b){var d=gd[4*b],e=v;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);L.uniform4fv(R(a),d)},wb:(a,b,c,d,e)=>{L.uniform4i(R(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){b*=4;for(var d=jd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],
d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);L.uniform4iv(R(a),d)},ub:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=gd[b],f=0;f<b;f+=4)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2]}else e=v.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(R(a),!!c,e)},tb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=gd[b],f=0;f<b;f+=9)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2],e[f+4]=v[d+(4*f+16)>>
2],e[f+5]=v[d+(4*f+20)>>2],e[f+6]=v[d+(4*f+24)>>2],e[f+7]=v[d+(4*f+28)>>2],e[f+8]=v[d+(4*f+32)>>2]}else e=v.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(R(a),!!c,e)},sb:ld,rb:md,qb:a=>{L.validateProgram(M[a])},ob:(a,b)=>L.vertexAttrib1f(a,b),nb:(a,b)=>{L.vertexAttrib1f(a,v[b>>2])},mb:(a,b,c)=>L.vertexAttrib2f(a,b,c),lb:(a,b)=>{L.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},kb:(a,b,c,d)=>L.vertexAttrib3f(a,b,c,d),jb:(a,b)=>{L.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},ib:(a,b,c,d,e)=>L.vertexAttrib4f(a,
b,c,d,e),hb:(a,b)=>{L.vertexAttrib4f(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Ud:(a,b)=>{L.vertexAttribDivisor(a,b)},gb:nd,fb:od,Sa:a=>{var b=p.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ta:pd,va:(a,b,c)=>{a=Fb(a);if(!a)return-4;a.width=b;a.height=c;return 0},
Z:(a,b,c,d)=>rd(a,b,c,d),$:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=Fb(a);if(!a)return-4;td(a,b,c,d,"webkitfullscreenchange");return td(a,b,c,d,"fullscreenchange")},T:(a,b,c)=>pd()?-1:ud(a,b,c,26,"gamepadconnected"),S:(a,b,c)=>pd()?-1:ud(a,b,c,27,"gamepaddisconnected"),_:(a,b,c,d)=>vd(a,b,c,d),U:(a,b,c,d)=>wd(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>wd(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>wd(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>wd(a,b,c,d,22,"touchstart"),ya:a=>document.title=a?z(p,a):"",za:a=>
wf(b=>xd(b,a)),P:a=>{fa=a;Bb(a)},A:function(a){try{var b=G(a);rb(b);return 0}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return c.te}},Wa:function(a,b,c,d){try{a:{var e=G(a);a=b;for(var f,g=b=0;g<c;g++){var n=u[a>>2],r=u[a+4>>2];a+=8;var q=e,A=n,w=r,B=f,va=m;if(0>w||0>B)throw new D(28);if(null===q.fd)throw new D(8);if(1===(q.flags&2097155))throw new D(8);if(16384===(q.node.mode&61440))throw new D(31);if(!q.le.read)throw new D(28);var Le="undefined"!=typeof B;if(!Le)B=q.position;
else if(!q.seekable)throw new D(70);var Me=q.le.read(q,va,A,w,B);Le||(q.position+=Me);var qb=Me;if(0>qb){var Ne=-1;break a}b+=qb;if(qb<r)break;"undefined"!=typeof f&&(f+=qb)}Ne=b}u[d>>2]=Ne;return 0}catch(Xb){if("undefined"==typeof I||"ErrnoError"!==Xb.name)throw Xb;return Xb.te}},Ta:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=G(a);sb(e,b,c);ja[d>>3]=BigInt(e.position);e.zf&&0===b&&0===c&&(e.zf=null);return 0}catch(f){if("undefined"==typeof I||
"ErrnoError"!==f.name)throw f;return f.te}},Va:function(a,b,c,d){try{a:{var e=G(a);a=b;for(var f,g=b=0;g<c;g++){var n=u[a>>2],r=u[a+4>>2];a+=8;var q=tb(e,m,n,r,f);if(0>q){var A=-1;break a}b+=q;if(q<r)break;"undefined"!=typeof f&&(f+=q)}A=b}u[d>>2]=A;return 0}catch(w){if("undefined"==typeof I||"ErrnoError"!==w.name)throw w;return w.te}},s:gc,w:hc,g:ic,b:jc,d:kc,Ub:lc,j:mc,p:nc,B:oc,C:pc,Xa:qc,Fa:rc,Ka:sc,Ca:tc,Ha:uc,Ic:vc,Ja:wc,pb:xc,Tc:yc,Rd:zc,Gd:Bc,D:Cc,e:Dc,eb:Ec,k:Fc,Ma:Gc,o:Ic,xc:Kc,Aa:Lc,v:Mc,
Da:Pc,x:Qc,i:Tc,n:Wc,Ba:Zc,Na:$c,Ia:bd,Ga:cd,La:dd,q:ed,h:fd,Y:hd,ha:kd,Ea:ld,y:md,f:nd,r:od,t:(a,b,c,d)=>{var e;for(e=0;e<W.length&&null!==W[e];e++);0<e&&y("glfwCreateWindow only supports one window at time currently");var f=e+1;if(0>=a||0>=b)f=0;else{d?Gd():(V(h.canvas,a,b),Sd());for(e=0;e<W.length&&null==W[e];e++);d=h.canvas;var g=0<T[139265];e==W.length&&(g?Dd(d):Ad());!h.ctx&&g?f=0:(a=new Td(f,a,b,d.width,d.height,c),f-1==W.length?W.push(a):W[f-1]=a,Y=a,df(),f=a.id)}return f},oa:()=>{T={...te}},
u:()=>1,a:()=>performance.now()/1E3-qe,na:(a,b)=>t[b>>2]=0,pa:()=>{if(W)return 1;qe=performance.now()/1E3;T={...te};W=[];Y=null;pe=cf();window.addEventListener("gamepadconnected",Ae,!0);window.addEventListener("gamepaddisconnected",Be,!0);window.addEventListener("keydown",Ce,!0);window.addEventListener("keypress",we,!0);window.addEventListener("keyup",De,!0);window.addEventListener("blur",Ee,!0);re=window.matchMedia("(resolution: "+cf()+"dppx)");re.addEventListener("change",ef);var a=h.canvas;a.addEventListener("touchmove",
Ge,!0);a.addEventListener("touchstart",Oe,!0);a.addEventListener("touchcancel",Pe,!0);a.addEventListener("touchend",Pe,!0);a.addEventListener("mousemove",Ge,!0);a.addEventListener("mousedown",Oe,!0);a.addEventListener("mouseup",Pe,!0);a.addEventListener("wheel",Qe,!0);a.addEventListener("mousewheel",Qe,!0);a.addEventListener("mouseenter",He,!0);a.addEventListener("mouseleave",Ie,!0);a.addEventListener("drop",Xe,!0);a.addEventListener("dragover",Ye,!0);Gd=Ze;Od=bf;V=$e;Rd.push((b,c)=>{if(af()){var d=
h.canvas;Se(d.clientWidth,d.clientHeight,b,c)}else Se(b,c,b,c)});return 1},aa:()=>0,fa:(a,b)=>{if(a=X(a)){var c=a.Ye;a.Ye=b;b=c}else b=null;return b},ba:(a,b)=>{a=X(a);if(!a)return null;var c=a.Oe;a.Oe=b;return c},da:(a,b)=>{if(a=X(a)){var c=a.Se;a.Se=b;b=c}else b=null;return b},ia:(a,b)=>{if(a=X(a)){var c=a.Te;a.Te=b;b=c}else b=null;return b},qa:a=>{var b=oe;oe=a;return b},ga:(a,b)=>{if(a=X(a)){var c=a.bf;a.bf=b;b=c}else b=null;return b},ea:(a,b)=>{if(a=X(a)){var c=a.jf;a.jf=b;b=c}else b=null;return b},
ca:(a,b)=>{if(a=X(a)){var c=a.mf;a.mf=b;b=c}else b=null;return b},ja:(a,b)=>{a=X(a);if(!a)return null;var c=a.eg;a.eg=b;return c},ka:(a,b)=>{a=X(a);if(!a)return null;var c=a.fg;a.fg=b;return c},R:(a,b)=>{if(a=X(a))a.vg=b},la:(a,b)=>{if(a=X(a)){var c=a.pf;a.pf=b;b=c}else b=null;return b},ua:()=>{},ma:()=>{window.removeEventListener("gamepadconnected",Ae,!0);window.removeEventListener("gamepaddisconnected",Be,!0);window.removeEventListener("keydown",Ce,!0);window.removeEventListener("keypress",we,!0);
window.removeEventListener("keyup",De,!0);window.removeEventListener("blur",Ee,!0);var a=h.canvas;a.removeEventListener("touchmove",Ge,!0);a.removeEventListener("touchstart",Oe,!0);a.removeEventListener("touchcancel",Pe,!0);a.removeEventListener("touchend",Pe,!0);a.removeEventListener("mousemove",Ge,!0);a.removeEventListener("mousedown",Oe,!0);a.removeEventListener("mouseup",Pe,!0);a.removeEventListener("wheel",Qe,!0);a.removeEventListener("mousewheel",Qe,!0);a.removeEventListener("mouseenter",He,
!0);a.removeEventListener("mouseleave",Ie,!0);a.removeEventListener("drop",Xe,!0);a.removeEventListener("dragover",Ye,!0);re&&re.removeEventListener("change",ef);a.width=a.height=1;Y=W=null},c:(a,b)=>{T[a]=b},Oa:Bb};
function Ff(){function a(){h.calledRun=!0;if(!l){if(!h.noFSInit&&!Za){var b,c;Za=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?vb("stdin",b):ob("/dev/tty","/dev/stdin");c?vb("stdout",null,c):ob("/dev/tty","/dev/stdout");d?vb("stderr",null,d):ob("/dev/tty1","/dev/stderr");pb("/dev/stdin",0);pb("/dev/stdout",1);pb("/dev/stderr",1)}Gf.be();$a=!1;h.onRuntimeInitialized?.();if(!h.noInitialRun){var d=Cf;try{var e=d(0,0);fa=e;Bb(e)}catch(f){Ab(f)}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)e=
h.postRun.shift(),sa.push(e);ra(sa)}}if(0<wa)xa=Ff;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();ra(ta);0<wa?xa=Ff:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}var Gf;
(async function(){function a(c){var d=Gf=c.exports;c={};for(let [e,f]of Object.entries(d))"function"==typeof f?(d=hf(f),c[e]=d):c[e]=f;c=Gf=c;Cf=h._main=c.ce;Q=c.de;We=c.ee;Df=c.fe;dynCall_vii=c.ge;Re=c.he;xe=c.ie;Je=c.je;Fe=c.ke;qd=c.me;dynCall_vi=c.ne;dynCall_v=c.ue;dynCall_iii=c.we;ff=c.Ae;yf=c.He;mf=c.Ie;xf=c.Je;zf=c.Ke;la=c.ae;ka();wa--;h.monitorRunDependencies?.(wa);0==wa&&xa&&(c=xa,xa=null,c());return Gf}wa++;h.monitorRunDependencies?.(wa);var b={a:Ef};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ma??=h.locateFile?h.locateFile("particle_storm.wasm",ba):ba+"particle_storm.wasm";return a((await pa(b)).instance)})();Ff();
